# Generated by Django 5.0 on 2024-09-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
