# Generated by Django 5.0 on 2024-08-28 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='college_id',
            new_name='college',
        ),
    ]
