# Generated by Django 5.0 on 2024-09-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0003_building_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
